web:
  build: .
  ports:
    - 80:80
  volumes:
    - .:/var/www/html/
  links:
    - mysql_database:mysql
    - redis_cache:redis

mysql_database:
  image: mysql/mysql-server
  environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./data:/var/lib/mysql

redis_cache:
  image: redis:latest